---
version: "3"
services:
  # --- Authentication Server
  mysql.keycloak.local:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  keycloak.local:
    image: jboss/keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql.keycloak.local
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      # JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 8080:8080
    depends_on:
      - mysql.keycloak.local
  # --- Application
  api.esearch.local:
    build: containers/web
    ports:
      - 80:80
      - 443:443
    environment:
      SERVER_NAME: "api.esearch.local"
      SERVER_ADMIN: "webmaster@esearch.local"
      DOCUMENT_ROOT: "/var/www/html/server/public"

      # Database
      DB_CONNECTION: "sqlite"
      DB_DATABASE: "/var/www/html/server/storage/db/database.sqlite"

      # ElasticSearch
      ELASTICSEARCH_HOST: "es.esearch.local"

      # OpenID
      OPENID_CLIENT_ID: "esearch"
      OPENID_CLIENT_SECRET: ""
      OPENID_URL_REDIRECT: "https://api.esearch.local/auth/callback"
      OPENID_URL_AUTH: "http://keycloak.local:8080/auth/realms/master/protocol/openid-connect/auth"
      OPENID_URL_TOKEN: "http://keycloak.local:8080/auth/realms/master/protocol/openid-connect/token"
      OPENID_URL_KEYS: "http://keycloak.local:8080/auth/realms/master/protocol/openid-connect/certs"
    volumes:
      - ./../../app:/var/www/html
  es.esearch.local:
    image: "elasticsearch:6.4.2"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: "single-node"
